# Team Task

In [21]:
#Importing the Libraries
import pandas as pd
import numpy as np

In [35]:
#Reading the Datasets
population = pd.read_csv("covid_county_population_usafacts.csv")
confirmed_cases = pd.read_csv("covid_confirmed_usafacts.csv")
deaths = pd.read_csv("covid_deaths_usafacts.csv")

In [23]:
population.head(5)

   countyFIPS            County Name State  population
0           0  Statewide Unallocated    AL           0
1        1001         Autauga County    AL       55869
2        1003         Baldwin County    AL      223234
3        1005         Barbour County    AL       24686
4        1007            Bibb County    AL       22394

In [24]:
confirmed_cases.head(5)

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-01-27,2023-01-28,2023-01-29,2023-01-30,2023-01-31,2023-02-01,2023-02-02,2023-02-03,2023-02-04,2023-02-05
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,19471,19471,19471,19471,19471,19471,19530,19530,19530,19530
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,68983,68983,68983,68983,68983,68983,69187,69187,69187,69187
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,7299,7299,7299,7299,7299,7299,7339,7339,7339,7339
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,7919,7919,7919,7919,7919,7919,7967,7967,7967,7967

In [25]:
deaths.head(5)

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-01-27,2023-01-28,2023-01-29,2023-01-30,2023-01-31,2023-02-01,2023-02-02,2023-02-03,2023-02-04,2023-02-05
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,230,230,230,230,230,230,230,230,230,230
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,723,723,723,723,723,723,723,723,723,723
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,103,103,103,103,103,103,103,103,103,103
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,109,109,109,109,109,109,109,109,109,109

# Data Cleaning

In [26]:
#Getting rid of spaces on the right side of County Names
population["County Name"] = population["County Name"].str.rstrip()
confirmed_cases["County Name"] = confirmed_cases["County Name"].str.rstrip()
deaths["County Name"] = deaths["County Name"].str.rstrip()

In [27]:
#Function to update county names to be able to merge with other covid data
def update_county_name(city_name):
    if city_name.endswith("City"):
        return city_name
    elif city_name.startswith("City of"):
        return city_name[8:] + " City"
    elif city_name.startswith("City and County of"):
        return city_name[19:] + " county"
    elif city_name.startswith("City and Borough of"):
        return city_name[20:] + " City and Borough"
    else:
        return city_name

confirmed_cases["County Name"] = confirmed_cases["County Name"].apply(update_county_name)
deaths["County Name"] = deaths["County Name"].apply(update_county_name)

In [38]:
#Function to update county names to be able to merge with other covid data
def update_county_name_for_population(city_name):
    if city_name.endswith("City"):
        return city_name
    elif city_name.startswith("City of"):
        return city_name[8:] + " City"
    elif city_name.startswith("City and County of"):
        return city_name[19:] + " county"
    elif city_name.startswith("City and Borough of"):
        return city_name[20:] + " City and Borough"
    else:
        return city_name

population["County Name"] = population["County Name"].apply(update_county_name_for_population)

In [37]:
confirmed_cases["County Name"] = np.where(confirmed_cases["County Name"] == "Town and County of Nantucket", "Nantucket County", confirmed_cases["County Name"])
confirmed_cases["County Name"] = np.where(confirmed_cases["County Name"] == "Prince of Wales - Hyder Census Area", "Prince of Wales-Hyder Census Area", confirmed_cases["County Name"])
confirmed_cases["County Name"] = np.where(confirmed_cases["County Name"] == "Consolidated Municipality of Carson City", "Carson City", confirmed_cases["County Name"])
confirmed_cases["County Name"] = np.where(confirmed_cases["County Name"] == "Municipality of Skagway", "Skagway Municipality", confirmed_cases["County Name"])

population["County Name"] = np.where(population["County Name"] == "DoÃ±a Ana County", "Dona Ana County", population["County Name"])
population["County Name"] = np.where(population["County Name"] == "La Salle Parish", "LaSalle Parish", population["County Name"])  #Broomfield County and City
population["County Name"] = np.where(population["County Name"] == "Broomfield County and City", "Broomfield County", population["County Name"])
population["County Name"] = np.where(population["County Name"] == "Matthews County", "Mathews County", population["County Name"])

deaths["County Name"] = np.where(deaths["County Name"] == "Town and County of Nantucket", "Nantucket County", deaths["County Name"])
deaths["County Name"] = np.where(deaths["County Name"] == "Prince of Wales - Hyder Census Area", "Prince of Wales-Hyder Census Area", deaths["County Name"])
deaths["County Name"] = np.where(deaths["County Name"] == "Consolidated Municipality of Carson City", "Carson City", deaths["County Name"])
deaths["County Name"] = np.where(deaths["County Name"] == "Municipality of Skagway", "Skagway Municipality", deaths["County Name"])

In [36]:
#lower casing county names for merging into a super covid dataset
population["County Name"] = population["County Name"].str.lower()
confirmed_cases["County Name"] = confirmed_cases["County Name"].str.lower()
deaths["County Name"] = deaths["County Name"].str.lower()

In [33]:
cases_and_deaths_df = cases.merge(deaths, on=["countyFIPS", "County Name", "State", "StateFIPS"])

In [34]:
cases_and_deaths_df = cases_and_deaths_df.merge(population, on=["countyFIPS", "County Name", "State"])

In [ ]:
#Save the final data set.
cases_and_deaths_df.to_csv("covid19_final_superdata.csv", index=False)